import { NextRequest, NextResponse } from 'next/server'
import { getPayload } from 'payload'
import config from '@payload-config'
import Stripe from 'stripe'
import { sendOrderConfirmationEmail } from '@/lib/email'
import { calculateShipping } from '@/lib/shipping/calculator'

const stripe = process.env.STRIPE_SECRET_KEY
  ? new Stripe(process.env.STRIPE_SECRET_KEY, { apiVersion: '2026-01-28.clover' })
  : null

interface OrderItem {
  product: string
  productName: string
  sku: string
  quantity: number
  unitPrice: number
  lineTotal: number
}

interface OrderRequest {
  customer: {
    name: string
    email: string
    phone?: string
    company: string
  }
  shipping: {
    address: string
    city: string
    state: string
    postalCode: string
    country: string
  }
  items: OrderItem[]
  subtotal: number
  shippingCost: number
  total: number
  currency: string
  paymentMethod: 'stripe' | 'paypal' | 'bank-transfer'
  shippingMethodCode?: string
  customerNotes?: string
}

export async function POST(req: NextRequest) {
  try {
    const body: OrderRequest = await req.json()

    // Basic validation
    if (!body.customer?.name || !body.customer?.email || !body.customer?.company) {
      return NextResponse.json({ error: 'Customer name, email, and company are required' }, { status: 400 })
    }
    if (!body.items || body.items.length === 0) {
      return NextResponse.json({ error: 'At least one item is required' }, { status: 400 })
    }
    if (!body.shipping?.address || !body.shipping?.city || !body.shipping?.postalCode) {
      return NextResponse.json({ error: 'Shipping address is required' }, { status: 400 })
    }

    // Recalculate totals server-side for integrity
    let subtotal = 0
    for (const item of body.items) {
      subtotal += item.unitPrice * item.quantity
    }

    // Server-side shipping calculation
    let shippingCost = 0
    let shippingMethodCode = ''
    let shippingMethodName = ''
    let estimatedShipDate = ''
    let estimatedDeliveryDate = ''
    let totalWeight = 0

    if (body.shippingMethodCode) {
      // Use new shipping calculator
      const shippingItems = body.items.map(item => ({
        productId: item.product,
        quantity: item.quantity,
      }))
      const country = body.shipping.country || 'US'
      const calcResult = await calculateShipping(shippingItems, country, subtotal)

      if (calcResult.success && calcResult.methods.length > 0) {
        const selectedMethod = calcResult.methods.find(m => m.code === body.shippingMethodCode)
          || calcResult.methods[0]

        shippingCost = selectedMethod.cost
        shippingMethodCode = selectedMethod.code
        shippingMethodName = selectedMethod.name
        estimatedShipDate = calcResult.estimatedShipDate
        estimatedDeliveryDate = selectedMethod.estimatedDeliveryDate
        totalWeight = calcResult.totalWeight
      } else {
        // Fallback if calculation fails
        shippingCost = subtotal >= 200 ? 0 : 25
      }
    } else {
      // Legacy fallback (no method selected)
      shippingCost = subtotal >= 200 ? 0 : 25
    }

    const total = subtotal + shippingCost

    const payload = await getPayload({ config })

    // Create order in Payload (order first, pay second)
    const order = await payload.create({
      collection: 'orders',
      draft: false,
      data: {
        orderNumber: '', // auto-generated by beforeValidate hook
        status: 'pending',
        paymentStatus: 'unpaid',
        customer: {
          name: body.customer.name,
          email: body.customer.email,
          phone: body.customer.phone || '',
          company: body.customer.company,
        },
        items: body.items.map(item => ({
          product: item.product,
          productName: item.productName,
          sku: item.sku,
          quantity: item.quantity,
          unitPrice: item.unitPrice,
          lineTotal: item.unitPrice * item.quantity,
        })),
        shipping: {
          address: body.shipping.address,
          city: body.shipping.city,
          state: body.shipping.state,
          postalCode: body.shipping.postalCode,
          country: body.shipping.country || 'US',
          shippingMethodCode,
          shippingMethodName,
          estimatedShipDate,
          estimatedDeliveryDate,
          totalWeight,
        },
        subtotal,
        shippingCost,
        total,
        currency: (body.currency || 'USD') as 'USD' | 'HKD' | 'EUR' | 'GBP' | 'CAD' | 'CNY',
        payment: {
          method: body.paymentMethod,
        },
        customerNotes: body.customerNotes || '',
      },
    })

    const orderNumber = order.orderNumber as string

    // Send confirmation emails (fire-and-forget)
    sendOrderConfirmationEmail({
      orderNumber,
      customerName: body.customer.name,
      customerEmail: body.customer.email,
      company: body.customer.company,
      total,
      currency: body.currency || 'USD',
      paymentMethod: body.paymentMethod,
      itemCount: body.items.length,
    }).catch(err => console.error('Email send error:', err))

    // If Stripe payment, create Checkout Session
    if (body.paymentMethod === 'stripe') {
      if (!stripe) {
        return NextResponse.json({ error: 'Online payment is not configured' }, { status: 500 })
      }

      const serverUrl = process.env.NEXT_PUBLIC_SERVER_URL || 'https://machrio.com'

      const session = await stripe.checkout.sessions.create({
        mode: 'payment',
        customer_email: body.customer.email,
        metadata: {
          orderNumber,
          orderId: order.id,
        },
        line_items: body.items.map(item => ({
          price_data: {
            currency: (body.currency || 'USD').toLowerCase(),
            product_data: {
              name: item.productName,
              description: `SKU: ${item.sku}`,
            },
            unit_amount: Math.round(item.unitPrice * 100), // cents
          },
          quantity: item.quantity,
        })).concat(
          shippingCost > 0
            ? [{
                price_data: {
                  currency: (body.currency || 'USD').toLowerCase(),
                  product_data: {
                    name: 'Shipping',
                    description: shippingMethodName || 'Shipping fee',
                  },
                  unit_amount: Math.round(shippingCost * 100),
                },
                quantity: 1,
              }]
            : []
        ),
        success_url: `${serverUrl}/order/${orderNumber}?payment=success`,
        cancel_url: `${serverUrl}/order/${orderNumber}?payment=cancelled`,
      })

      // Store Stripe session ID on the order
      await payload.update({
        collection: 'orders',
        id: order.id,
        data: {
          payment: {
            method: 'stripe',
            stripeSessionId: session.id,
          },
        },
      })

      return NextResponse.json({
        orderNumber,
        orderId: order.id,
        stripeUrl: session.url,
      })
    }

    // Bank transfer or PayPal - return the order number
    // For PayPal, the frontend will call /api/paypal/create-order separately
    return NextResponse.json({
      orderNumber,
      orderId: order.id,
    })
  } catch (err) {
    console.error('Order creation error:', err)
    return NextResponse.json(
      { error: 'Failed to create order' },
      { status: 500 }
    )
  }
}
