/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    categories: Category;
    products: Product;
    brands: Brand;
    media: Media;
    orders: Order;
    customers: Customer;
    quotes: Quote;
    'bank-accounts': BankAccount;
    'rfq-submissions': RfqSubmission;
    'contact-submissions': ContactSubmission;
    'shipping-methods': ShippingMethod;
    'shipping-rates': ShippingRate;
    'free-shipping-rules': FreeShippingRule;
    'verification-codes': VerificationCode;
    'account-sessions': AccountSession;
    productViews: ProductView;
    articles: Article;
    pages: Page;
    industries: Industry;
    redirects: Redirect;
    'glossary-terms': GlossaryTerm;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    'bank-accounts': BankAccountsSelect<false> | BankAccountsSelect<true>;
    'rfq-submissions': RfqSubmissionsSelect<false> | RfqSubmissionsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'shipping-methods': ShippingMethodsSelect<false> | ShippingMethodsSelect<true>;
    'shipping-rates': ShippingRatesSelect<false> | ShippingRatesSelect<true>;
    'free-shipping-rules': FreeShippingRulesSelect<false> | FreeShippingRulesSelect<true>;
    'verification-codes': VerificationCodesSelect<false> | VerificationCodesSelect<true>;
    'account-sessions': AccountSessionsSelect<false> | AccountSessionsSelect<true>;
    productViews: ProductViewsSelect<false> | ProductViewsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'glossary-terms': GlossaryTermsSelect<false> | GlossaryTermsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'admin' | 'editor' | 'sales';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  /**
   * Display name for the category
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated)
   */
  slug: string;
  /**
   * Parent category (leave empty for top-level)
   */
  parent?: (string | null) | Category;
  /**
   * SEO description (minimum 150 words recommended)
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short description for cards (max 160 chars)
   */
  shortDescription?: string | null;
  /**
   * SEO intro paragraph shown at top of category page (expandable, 150-200 words)
   */
  introContent?: string | null;
  /**
   * How to choose guide - shown at bottom before FAQ (200-300 words)
   */
  buyingGuide?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Frequently Asked Questions (4-6 recommended for SEO)
   */
  faq?:
    | {
        /**
         * The question (e.g., "What certifications should I look for?")
         */
        question: string;
        /**
         * The answer (2-4 sentences, include relevant keywords)
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Category banner image
   */
  heroImage?: (string | null) | Media;
  /**
   * Category icon for navigation
   */
  icon?: (string | null) | Media;
  /**
   * Emoji icon for category cards (e.g. 🛡️, 📦)
   */
  iconEmoji?: string | null;
  /**
   * Show on homepage
   */
  featured?: boolean | null;
  /**
   * Order for sorting (lower = first)
   */
  displayOrder?: number | null;
  /**
   * Configure which filter dimensions to show
   */
  facetGroups?:
    | {
        facetName: 'material' | 'size' | 'color' | 'brand' | 'certification' | 'priceRange' | 'availability';
        /**
         * Show expanded by default
         */
        expanded?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Custom filter attributes for L3 categories (values aggregated from product specifications)
   */
  customFilterAttributes?:
    | {
        /**
         * Attribute name (e.g., Abrasive Grade)
         */
        name: string;
        /**
         * URL-safe key (e.g., abrasive-grade)
         */
        key: string;
        displayOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * SEO overrides (leave empty to use defaults)
   */
  seo?: {
    /**
     * Override default title (max 60 chars)
     */
    metaTitle?: string | null;
    /**
     * Override default description (max 160 chars)
     */
    metaDescription?: string | null;
  };
  /**
   * Additional SEO content for bottom of page
   */
  seoContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Number of products (auto-calculated)
   */
  productCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe this image for accessibility and SEO
   */
  alt: string;
  /**
   * Optional caption
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * URL-safe identifier
   */
  slug: string;
  /**
   * Internal product code
   */
  sku: string;
  status: 'draft' | 'published' | 'discontinued';
  /**
   * How customers can purchase
   */
  purchaseMode: 'both' | 'buy-online' | 'rfq-only';
  /**
   * Full product name
   */
  name: string;
  /**
   * Short name for listings (optional)
   */
  shortName?: string | null;
  /**
   * Main category (used in URL)
   */
  primaryCategory: string | Category;
  /**
   * Product brand (optional)
   */
  brand?: (string | null) | Brand;
  /**
   * Additional categories
   */
  categories?: (string | Category)[] | null;
  /**
   * Brief description (50+ words, used for meta description)
   */
  shortDescription: string;
  industries?:
    | (
        | 'manufacturing'
        | 'construction'
        | 'automotive'
        | 'healthcare'
        | 'food-beverage'
        | 'warehouse'
        | 'oil-gas'
        | 'mining'
      )[]
    | null;
  pricing?: {
    /**
     * Cost price (for margin calculation)
     */
    costPrice?: number | null;
    /**
     * Selling price (leave empty for RFQ-only)
     */
    basePrice?: number | null;
    /**
     * Original price (strikethrough)
     */
    compareAtPrice?: number | null;
    currency?: ('USD' | 'CAD') | null;
    /**
     * e.g., per piece, per box, per 100
     */
    priceUnit?: string | null;
    /**
     * Volume discount tiers (auto-generated if empty)
     */
    tieredPricing?:
      | {
          /**
           * Min qty
           */
          minQty: number;
          /**
           * Max qty
           */
          maxQty?: number | null;
          /**
           * Unit price
           */
          unitPrice: number;
          id?: string | null;
        }[]
      | null;
  };
  availability: 'in-stock' | 'made-to-order' | 'contact';
  /**
   * e.g., 2-3 weeks, Ships in 1 day
   */
  leadTime?: string | null;
  /**
   * Minimum order qty
   */
  minOrderQuantity?: number | null;
  /**
   * Units per package
   */
  packageQty?: number | null;
  /**
   * e.g., box, case, roll
   */
  packageUnit?: string | null;
  /**
   * Shipping weight and processing
   */
  shippingInfo?: {
    /**
     * Weight in kg
     */
    weight?: number | null;
    /**
     * Days to ship
     */
    processingTime?: number | null;
  };
  externalImageUrl?: string | null;
  additionalImageUrls?: string[] | null;
  primaryImage?: (string | null) | Media;
  images?: (string | Media)[] | null;
  /**
   * PDF datasheet/specification document
   */
  datasheet?: (string | null) | Media;
  /**
   * Technical specifications
   */
  specifications?:
    | {
        label: string;
        value: string;
        /**
         * e.g., kg, mm
         */
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Full product description (300+ words for SEO)
   */
  fullDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * SEO overrides
   */
  seo?: {
    /**
     * Custom meta title (auto-generated if empty)
     */
    metaTitle?: string | null;
    /**
     * Custom meta description
     */
    metaDescription?: string | null;
    /**
     * Primary keyword for this product
     */
    focusKeyword?: string | null;
  };
  /**
   * Related products for cross-selling
   */
  relatedProducts?: (string | Product)[] | null;
  /**
   * Original product source URL (for tracking)
   */
  sourceUrl?: string | null;
  /**
   * Frequently Asked Questions (up to 3)
   */
  faq?:
    | {
        /**
         * FAQ question
         */
        question: string;
        /**
         * FAQ answer
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: string;
  name: string;
  slug: string;
  /**
   * Brand logo
   */
  logo?: (string | null) | Media;
  /**
   * Brand description (minimum 200 words for SEO)
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Official brand website URL
   */
  website?: string | null;
  /**
   * Show in featured brands section
   */
  featured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  orderNumber: string;
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  paymentStatus: 'unpaid' | 'paid' | 'refunded';
  /**
   * How this order was created
   */
  source?: ('direct' | 'rfq') | null;
  /**
   * Link to customer profile
   */
  customerRef?: (string | null) | Customer;
  customer: {
    name: string;
    email: string;
    phone?: string | null;
    company: string;
  };
  items: {
    product: string | Product;
    /**
     * Snapshot of product name at time of order
     */
    productName: string;
    sku: string;
    quantity: number;
    /**
     * Price per unit at time of order
     */
    unitPrice: number;
    lineTotal: number;
    id?: string | null;
  }[];
  shipping: {
    address: string;
    city: string;
    state: string;
    postalCode: string;
    /**
     * Country code, e.g. US, CA, HK, GB
     */
    country: string;
    method?: string | null;
    trackingNumber?: string | null;
    /**
     * Selected shipping method code, e.g. "standard", "economy"
     */
    shippingMethodCode?: string | null;
    /**
     * Snapshot of shipping method display name
     */
    shippingMethodName?: string | null;
    /**
     * Calculated ship date (ISO string)
     */
    estimatedShipDate?: string | null;
    /**
     * Calculated delivery date (ISO string)
     */
    estimatedDeliveryDate?: string | null;
    /**
     * Total chargeable weight in kg
     */
    totalWeight?: number | null;
  };
  subtotal: number;
  shippingCost?: number | null;
  tax?: number | null;
  total: number;
  currency?: ('USD' | 'HKD' | 'EUR' | 'GBP' | 'CAD' | 'CNY') | null;
  payment?: {
    method?: ('stripe' | 'bank-transfer') | null;
    /**
     * Stripe Checkout Session ID
     */
    stripeSessionId?: string | null;
    /**
     * Stripe Payment Intent ID
     */
    stripePaymentIntentId?: string | null;
    transactionId?: string | null;
  };
  /**
   * Notes from the customer at checkout
   */
  customerNotes?: string | null;
  assignedTo?: (string | null) | User;
  /**
   * Internal notes
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  /**
   * Company name
   */
  company: string;
  /**
   * Primary contact name
   */
  name: string;
  /**
   * Primary email (unique identifier)
   */
  email: string;
  phone?: string | null;
  /**
   * Job title
   */
  title?: string | null;
  /**
   * How this customer was first acquired
   */
  source?: ('direct' | 'rfq' | 'contact' | 'manual') | null;
  /**
   * Saved shipping addresses
   */
  shippingAddresses?:
    | {
        /**
         * e.g., Headquarters, Warehouse
         */
        label?: string | null;
        address: string;
        city: string;
        state: string;
        postalCode: string;
        /**
         * Country code, e.g. US, CA, HK
         */
        country: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Invoice / billing information
   */
  billingInfo?: {
    /**
     * Legal entity name for invoicing
     */
    companyLegalName?: string | null;
    /**
     * Tax ID / VAT number
     */
    taxId?: string | null;
    billingAddress?: string | null;
  };
  /**
   * e.g., VIP, Key Account, Follow Up
   */
  tags?: string[] | null;
  /**
   * Internal notes (not visible to customer)
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: string;
  quoteNumber: string;
  status: 'draft' | 'sent' | 'accepted' | 'converted' | 'expired' | 'rejected';
  /**
   * Source RFQ inquiry (leave empty for proactive quotes)
   */
  rfq?: (string | null) | RfqSubmission;
  customer: string | Customer;
  items: {
    product: string | Product;
    /**
     * Snapshot of product name
     */
    productName: string;
    sku: string;
    quantity: number;
    /**
     * Quoted unit price
     */
    unitPrice: number;
    /**
     * quantity × unitPrice
     */
    lineTotal: number;
    /**
     * Lead time, special conditions, etc.
     */
    notes?: string | null;
    id?: string | null;
  }[];
  subtotal: number;
  shippingCost?: number | null;
  tax?: number | null;
  total: number;
  currency?: ('USD' | 'CAD') | null;
  /**
   * Quote expiry date
   */
  validUntil: string;
  /**
   * Payment terms, delivery conditions, etc.
   */
  terms?: string | null;
  /**
   * Order created from this quote
   */
  convertedOrder?: (string | null) | Order;
  /**
   * Sales representative
   */
  assignedTo?: (string | null) | User;
  /**
   * Internal notes (not visible to customer)
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfq-submissions".
 */
export interface RfqSubmission {
  id: string;
  displayTitle?: string | null;
  submittedAt: string;
  customer: {
    name: string;
    email: string;
    phone?: string | null;
    company: string;
    /**
     * Job title
     */
    title?: string | null;
  };
  inquiry: {
    /**
     * Products the customer is inquiring about
     */
    products?: (string | Product)[] | null;
    /**
     * Requested quantity
     */
    quantity?: number | null;
    /**
     * Customer message/requirements
     */
    message: string;
    /**
     * Specification documents, drawings, etc.
     */
    attachments?: (string | Media)[] | null;
  };
  /**
   * Link to customer profile
   */
  customerRef?: (string | null) | Customer;
  /**
   * Quote created from this inquiry
   */
  quote?: (string | null) | Quote;
  status: 'new' | 'contacted' | 'quoted' | 'converted' | 'lost';
  /**
   * Sales representative
   */
  assignedTo?: (string | null) | User;
  /**
   * Internal notes (not visible to customer)
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  source?: {
    /**
     * Page where form was submitted
     */
    page?: string | null;
    /**
     * Referrer URL
     */
    referrer?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bank-accounts".
 */
export interface BankAccount {
  id: string;
  /**
   * Display name, e.g. "USD - HSBC Hong Kong"
   */
  accountName: string;
  /**
   * Country name in English, e.g. "Hong Kong", "United States"
   */
  country: string;
  /**
   * ISO 3166-1 alpha-2 code, e.g. "HK", "US", "DE"
   */
  countryCode: string;
  /**
   * Flag emoji, e.g. "🇭🇰", "🇺🇸"
   */
  flag?: string | null;
  currency:
    | 'USD'
    | 'HKD'
    | 'EUR'
    | 'GBP'
    | 'CAD'
    | 'CNY'
    | 'AUD'
    | 'NZD'
    | 'SGD'
    | 'AED'
    | 'MXN'
    | 'PHP'
    | 'IDR'
    | 'ILS'
    | 'DKK';
  bankName: string;
  beneficiaryName: string;
  /**
   * Account number, IBAN, or local account format
   */
  accountNumber: string;
  /**
   * Local routing code: IBAN (EU), Routing Number (US), BSB (AU), Sort Code (UK), etc.
   */
  localBankCode?: string | null;
  /**
   * Label for local code, e.g. "IBAN", "Routing Number", "BSB", "Sort Code"
   */
  localBankCodeLabel?: string | null;
  /**
   * SWIFT/BIC code for international transfers
   */
  swiftCode?: string | null;
  bankAddress?: string | null;
  /**
   * Any additional payment instructions
   */
  additionalInfo?: string | null;
  isActive?: boolean | null;
  /**
   * Lower numbers appear first
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  displayTitle?: string | null;
  submittedAt: string;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  subject: 'general' | 'support' | 'order' | 'return' | 'partnership' | 'other';
  message: string;
  status: 'new' | 'replied' | 'resolved';
  /**
   * Internal notes
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-methods".
 */
export interface ShippingMethod {
  id: string;
  /**
   * Display name, e.g. "Standard Air Shipping"
   */
  name: string;
  /**
   * Internal code, e.g. "standard", "economy"
   */
  code: string;
  /**
   * Transit time in calendar days (not displayed to buyer, used for ETA calculation)
   */
  transitDays: number;
  /**
   * Customer-facing description of shipping service
   */
  description?: string | null;
  isActive?: boolean | null;
  /**
   * Lower numbers appear first
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-rates".
 */
export interface ShippingRate {
  id: string;
  /**
   * Auto-generated from method + country
   */
  displayName?: string | null;
  /**
   * Which shipping method this rate applies to
   */
  shippingMethod: string | ShippingMethod;
  /**
   * ISO country code e.g. "US", "DE", "GB". Use "OTHER" as fallback for unlisted countries.
   */
  countryCode: string;
  /**
   * Display name e.g. "United States", "Germany"
   */
  countryName?: string | null;
  /**
   * Included base weight (kg)
   */
  baseWeight: number;
  /**
   * Cost for base weight (USD)
   */
  baseRate: number;
  /**
   * Cost per kg above base weight (USD)
   */
  additionalRate: number;
  /**
   * Flat handling/processing fee (USD)
   */
  handlingFee: number;
  isActive?: boolean | null;
  /**
   * Internal notes
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "free-shipping-rules".
 */
export interface FreeShippingRule {
  id: string;
  /**
   * e.g. "Economy Free Shipping $500+"
   */
  name: string;
  /**
   * Which shipping method this threshold applies to
   */
  shippingMethod: string | ShippingMethod;
  /**
   * Leave blank for global, or set ISO code (e.g. "US") for country-specific rule
   */
  countryCode?: string | null;
  /**
   * Minimum order subtotal (USD) to qualify for free shipping
   */
  minimumAmount: number;
  /**
   * Custom prompt template, e.g. "Add ${gap} more for free shipping!"
   */
  message?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-codes".
 */
export interface VerificationCode {
  id: string;
  email: string;
  code: string;
  expiresAt: string;
  attempts?: number | null;
  verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-sessions".
 */
export interface AccountSession {
  id: string;
  email: string;
  token: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product view logs for recommendation engine
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productViews".
 */
export interface ProductView {
  id: string;
  product: string | Product;
  /**
   * Anonymous session identifier (from cookie/localStorage)
   */
  sessionId: string;
  viewedAt: string;
  /**
   * Page URL that led to this product view
   */
  referrer?: string | null;
  /**
   * Browser user agent string
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog posts, buying guides, and knowledge articles for SEO and content marketing
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  /**
   * Article title — include target keyword naturally
   */
  title: string;
  /**
   * URL slug (auto-generated from title if left empty)
   */
  slug: string;
  /**
   * Short summary shown on cards and in meta description (max 300 chars)
   */
  excerpt: string;
  /**
   * Full article content. Use headings (H2, H3) for structure.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Direct answer in ~50 words. AI engines (ChatGPT, Perplexity, Google SGE) prioritize this for citations. Leave empty to skip.
   */
  quickAnswer?: string | null;
  /**
   * FAQ pairs generate FAQPage Schema for Google Rich Results and AI engine extraction.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary content category
   */
  category: 'buying-guide' | 'industry-insight' | 'how-to' | 'product-comparison';
  /**
   * Tags for filtering (e.g. "safety", "adhesives", "manufacturing")
   */
  tags?: string[] | null;
  /**
   * Author name displayed on the article
   */
  author?: string | null;
  /**
   * Featured image for article cards and hero section
   */
  featuredImage?: (string | null) | Media;
  /**
   * Only published articles appear on the site
   */
  status: 'draft' | 'published';
  /**
   * Publication date (auto-set when status changes to published)
   */
  publishedAt?: string | null;
  /**
   * Products to display at the bottom of the article
   */
  relatedProducts?: (string | Product)[] | null;
  /**
   * Related product categories for internal linking
   */
  relatedCategories?: (string | Category)[] | null;
  /**
   * SEO overrides (leave empty to auto-generate from title/excerpt)
   */
  seo?: {
    /**
     * Custom meta title (max 60 chars). Defaults to article title.
     */
    metaTitle?: string | null;
    /**
     * Custom meta description (max 160 chars). Defaults to excerpt.
     */
    metaDescription?: string | null;
  };
  /**
   * Estimated reading time in minutes (auto-calculated)
   */
  readingTime?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL path, e.g., about, faq, privacy
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Determines the rendering template
   */
  pageType: 'standard' | 'faq' | 'about' | 'contact' | 'support';
  /**
   * Optional hero/banner image at the top of the page
   */
  heroImage?: (string | null) | Media;
  /**
   * Main page content (Lexical rich text editor)
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * FAQ question-answer pairs (generates FAQPage JSON-LD)
   */
  faqItems?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Contact information displayed on the page
   */
  contactInfo?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    businessHours?: string | null;
  };
  /**
   * SEO overrides for this page
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
    /**
     * Prevent this page from being indexed by search engines
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: string;
  /**
   * e.g., Manufacturing, Construction
   */
  name: string;
  slug: string;
  status: 'draft' | 'published';
  heroImage?: (string | null) | Media;
  /**
   * Industry overview
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Industry pain points / challenges
   */
  challenges?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * How Machrio addresses these challenges
   */
  solutions?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Product categories relevant to this industry
   */
  featuredCategories?: (string | Category)[] | null;
  /**
   * Industry-specific FAQ (generates FAQPage schema)
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * Source path, e.g., /old-page
   */
  from: string;
  /**
   * Destination path, e.g., /new-page
   */
  to: string;
  type: '301' | '302';
  isActive?: boolean | null;
  /**
   * Reason for redirect
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Industrial glossary terms for SEO — "What is PPE", "What is LOTO", etc.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms".
 */
export interface GlossaryTerm {
  id: string;
  /**
   * The term or acronym (e.g. "PPE", "LOTO", "MRO")
   */
  term: string;
  /**
   * URL slug (auto-generated from term)
   */
  slug: string;
  /**
   * Full expanded name if the term is an acronym (e.g. "Personal Protective Equipment")
   */
  fullName?: string | null;
  /**
   * Concise 1-2 sentence definition shown at the top of the page
   */
  definition: string;
  /**
   * Detailed explanation, examples, standards, and best practices
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Topic category for grouping and filtering
   */
  category: 'safety' | 'maintenance' | 'materials' | 'procurement' | 'tools' | 'standards';
  /**
   * Related glossary terms for internal linking
   */
  relatedTerms?: (string | GlossaryTerm)[] | null;
  /**
   * Related product categories
   */
  relatedCategories?: (string | Category)[] | null;
  status: 'draft' | 'published';
  /**
   * SEO overrides
   */
  seo?: {
    /**
     * Custom meta title. Defaults to "What is [Term]? | Machrio"
     */
    metaTitle?: string | null;
    /**
     * Custom meta description. Defaults to definition.
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'brands';
        value: string | Brand;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'quotes';
        value: string | Quote;
      } | null)
    | ({
        relationTo: 'bank-accounts';
        value: string | BankAccount;
      } | null)
    | ({
        relationTo: 'rfq-submissions';
        value: string | RfqSubmission;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'shipping-methods';
        value: string | ShippingMethod;
      } | null)
    | ({
        relationTo: 'shipping-rates';
        value: string | ShippingRate;
      } | null)
    | ({
        relationTo: 'free-shipping-rules';
        value: string | FreeShippingRule;
      } | null)
    | ({
        relationTo: 'verification-codes';
        value: string | VerificationCode;
      } | null)
    | ({
        relationTo: 'account-sessions';
        value: string | AccountSession;
      } | null)
    | ({
        relationTo: 'productViews';
        value: string | ProductView;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'industries';
        value: string | Industry;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'glossary-terms';
        value: string | GlossaryTerm;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  description?: T;
  shortDescription?: T;
  introContent?: T;
  buyingGuide?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  heroImage?: T;
  icon?: T;
  iconEmoji?: T;
  featured?: T;
  displayOrder?: T;
  facetGroups?:
    | T
    | {
        facetName?: T;
        expanded?: T;
        id?: T;
      };
  customFilterAttributes?:
    | T
    | {
        name?: T;
        key?: T;
        displayOrder?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  seoContent?: T;
  productCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  sku?: T;
  status?: T;
  purchaseMode?: T;
  name?: T;
  shortName?: T;
  primaryCategory?: T;
  brand?: T;
  categories?: T;
  shortDescription?: T;
  industries?: T;
  pricing?:
    | T
    | {
        costPrice?: T;
        basePrice?: T;
        compareAtPrice?: T;
        currency?: T;
        priceUnit?: T;
        tieredPricing?:
          | T
          | {
              minQty?: T;
              maxQty?: T;
              unitPrice?: T;
              id?: T;
            };
      };
  availability?: T;
  leadTime?: T;
  minOrderQuantity?: T;
  packageQty?: T;
  packageUnit?: T;
  shippingInfo?:
    | T
    | {
        weight?: T;
        processingTime?: T;
      };
  externalImageUrl?: T;
  additionalImageUrls?: T;
  primaryImage?: T;
  images?: T;
  datasheet?: T;
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        unit?: T;
        id?: T;
      };
  fullDescription?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        focusKeyword?: T;
      };
  relatedProducts?: T;
  sourceUrl?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  description?: T;
  website?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  paymentStatus?: T;
  source?: T;
  customerRef?: T;
  customer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        company?: T;
      };
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        sku?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        id?: T;
      };
  shipping?:
    | T
    | {
        address?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        method?: T;
        trackingNumber?: T;
        shippingMethodCode?: T;
        shippingMethodName?: T;
        estimatedShipDate?: T;
        estimatedDeliveryDate?: T;
        totalWeight?: T;
      };
  subtotal?: T;
  shippingCost?: T;
  tax?: T;
  total?: T;
  currency?: T;
  payment?:
    | T
    | {
        method?: T;
        stripeSessionId?: T;
        stripePaymentIntentId?: T;
        transactionId?: T;
      };
  customerNotes?: T;
  assignedTo?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  company?: T;
  name?: T;
  email?: T;
  phone?: T;
  title?: T;
  source?: T;
  shippingAddresses?:
    | T
    | {
        label?: T;
        address?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        id?: T;
      };
  billingInfo?:
    | T
    | {
        companyLegalName?: T;
        taxId?: T;
        billingAddress?: T;
      };
  tags?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  quoteNumber?: T;
  status?: T;
  rfq?: T;
  customer?: T;
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        sku?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        notes?: T;
        id?: T;
      };
  subtotal?: T;
  shippingCost?: T;
  tax?: T;
  total?: T;
  currency?: T;
  validUntil?: T;
  terms?: T;
  convertedOrder?: T;
  assignedTo?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bank-accounts_select".
 */
export interface BankAccountsSelect<T extends boolean = true> {
  accountName?: T;
  country?: T;
  countryCode?: T;
  flag?: T;
  currency?: T;
  bankName?: T;
  beneficiaryName?: T;
  accountNumber?: T;
  localBankCode?: T;
  localBankCodeLabel?: T;
  swiftCode?: T;
  bankAddress?: T;
  additionalInfo?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfq-submissions_select".
 */
export interface RfqSubmissionsSelect<T extends boolean = true> {
  displayTitle?: T;
  submittedAt?: T;
  customer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        company?: T;
        title?: T;
      };
  inquiry?:
    | T
    | {
        products?: T;
        quantity?: T;
        message?: T;
        attachments?: T;
      };
  customerRef?: T;
  quote?: T;
  status?: T;
  assignedTo?: T;
  notes?: T;
  source?:
    | T
    | {
        page?: T;
        referrer?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  displayTitle?: T;
  submittedAt?: T;
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  subject?: T;
  message?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-methods_select".
 */
export interface ShippingMethodsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  transitDays?: T;
  description?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-rates_select".
 */
export interface ShippingRatesSelect<T extends boolean = true> {
  displayName?: T;
  shippingMethod?: T;
  countryCode?: T;
  countryName?: T;
  baseWeight?: T;
  baseRate?: T;
  additionalRate?: T;
  handlingFee?: T;
  isActive?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "free-shipping-rules_select".
 */
export interface FreeShippingRulesSelect<T extends boolean = true> {
  name?: T;
  shippingMethod?: T;
  countryCode?: T;
  minimumAmount?: T;
  message?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-codes_select".
 */
export interface VerificationCodesSelect<T extends boolean = true> {
  email?: T;
  code?: T;
  expiresAt?: T;
  attempts?: T;
  verified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-sessions_select".
 */
export interface AccountSessionsSelect<T extends boolean = true> {
  email?: T;
  token?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productViews_select".
 */
export interface ProductViewsSelect<T extends boolean = true> {
  product?: T;
  sessionId?: T;
  viewedAt?: T;
  referrer?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  quickAnswer?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  category?: T;
  tags?: T;
  author?: T;
  featuredImage?: T;
  status?: T;
  publishedAt?: T;
  relatedProducts?: T;
  relatedCategories?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  readingTime?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  pageType?: T;
  heroImage?: T;
  content?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
        businessHours?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  heroImage?: T;
  description?: T;
  challenges?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  solutions?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  featuredCategories?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  isActive?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms_select".
 */
export interface GlossaryTermsSelect<T extends boolean = true> {
  term?: T;
  slug?: T;
  fullName?: T;
  definition?: T;
  content?: T;
  category?: T;
  relatedTerms?: T;
  relatedCategories?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  /**
   * Top announcement bar displayed across the site
   */
  announcement?: {
    /**
     * Announcement message
     */
    text?: string | null;
    /**
     * Click destination URL (optional)
     */
    linkUrl?: string | null;
    isActive?: boolean | null;
  };
  /**
   * Homepage hero carousel banners
   */
  heroBanners?:
    | {
        image: string | Media;
        title?: string | null;
        subtitle?: string | null;
        /**
         * CTA button text, e.g., Shop Now
         */
        buttonText?: string | null;
        linkUrl: string;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Categories shown in Browse Categories section (overrides default displayOrder)
   */
  featuredCategories?: (string | Category)[] | null;
  /**
   * Mid-page promotional banner
   */
  promotionBanner?: {
    image?: (string | null) | Media;
    title?: string | null;
    linkUrl?: string | null;
    isActive?: boolean | null;
  };
  /**
   * Homepage SEO overrides
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName?: string | null;
  logo?: (string | null) | Media;
  favicon?: (string | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    /**
     * e.g., Mon-Fri 9AM-6PM EST
     */
    businessHours?: string | null;
  };
  socialLinks?:
    | {
        platform: 'linkedin' | 'facebook' | 'twitter' | 'instagram' | 'youtube';
        url: string;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footer?: {
    /**
     * e.g., © 2026 Machrio. All rights reserved.
     */
    copyrightText?: string | null;
    /**
     * Additional footer text or legal notice
     */
    additionalText?: string | null;
  };
  /**
   * Fallback SEO values when page-level SEO is not set
   */
  defaultSeo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Default Open Graph image
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  /**
   * Top navigation bar links
   */
  mainNav?:
    | {
        label: string;
        url: string;
        openInNewTab?: boolean | null;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Footer navigation groups
   */
  footerNav?:
    | {
        /**
         * Column heading, e.g., Customer Service, Company
         */
        groupTitle: string;
        links?:
          | {
              label: string;
              url: string;
              isActive?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  announcement?:
    | T
    | {
        text?: T;
        linkUrl?: T;
        isActive?: T;
      };
  heroBanners?:
    | T
    | {
        image?: T;
        title?: T;
        subtitle?: T;
        buttonText?: T;
        linkUrl?: T;
        isActive?: T;
        id?: T;
      };
  featuredCategories?: T;
  promotionBanner?:
    | T
    | {
        image?: T;
        title?: T;
        linkUrl?: T;
        isActive?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  favicon?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
        businessHours?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        isActive?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        copyrightText?: T;
        additionalText?: T;
      };
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        isActive?: T;
        id?: T;
      };
  footerNav?:
    | T
    | {
        groupTitle?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              isActive?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}