/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    categories: Category;
    products: Product;
    brands: Brand;
    media: Media;
    orders: Order;
    'bank-accounts': BankAccount;
    'rfq-submissions': RfqSubmission;
    'contact-submissions': ContactSubmission;
    'shipping-methods': ShippingMethod;
    'shipping-rates': ShippingRate;
    'free-shipping-rules': FreeShippingRule;
    'verification-codes': VerificationCode;
    'account-sessions': AccountSession;
    productViews: ProductView;
    articles: Article;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'bank-accounts': BankAccountsSelect<false> | BankAccountsSelect<true>;
    'rfq-submissions': RfqSubmissionsSelect<false> | RfqSubmissionsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'shipping-methods': ShippingMethodsSelect<false> | ShippingMethodsSelect<true>;
    'shipping-rates': ShippingRatesSelect<false> | ShippingRatesSelect<true>;
    'free-shipping-rules': FreeShippingRulesSelect<false> | FreeShippingRulesSelect<true>;
    'verification-codes': VerificationCodesSelect<false> | VerificationCodesSelect<true>;
    'account-sessions': AccountSessionsSelect<false> | AccountSessionsSelect<true>;
    productViews: ProductViewsSelect<false> | ProductViewsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'admin' | 'editor' | 'sales';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  /**
   * Display name for the category
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated)
   */
  slug: string;
  /**
   * Parent category (leave empty for top-level)
   */
  parent?: (string | null) | Category;
  /**
   * SEO description (minimum 150 words recommended)
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short description for cards (max 160 chars)
   */
  shortDescription?: string | null;
  /**
   * SEO intro paragraph shown at top of category page (expandable, 150-200 words)
   */
  introContent?: string | null;
  /**
   * How to choose guide - shown at bottom before FAQ (200-300 words)
   */
  buyingGuide?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Frequently Asked Questions (4-6 recommended for SEO)
   */
  faq?:
    | {
        /**
         * The question (e.g., "What certifications should I look for?")
         */
        question: string;
        /**
         * The answer (2-4 sentences, include relevant keywords)
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Category banner image
   */
  heroImage?: (string | null) | Media;
  /**
   * Category icon for navigation
   */
  icon?: (string | null) | Media;
  /**
   * Show on homepage
   */
  featured?: boolean | null;
  /**
   * Order for sorting (lower = first)
   */
  displayOrder?: number | null;
  /**
   * Configure which filter dimensions to show
   */
  facetGroups?:
    | {
        facetName: 'material' | 'size' | 'color' | 'brand' | 'certification' | 'priceRange' | 'availability';
        /**
         * Show expanded by default
         */
        expanded?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * SEO overrides (leave empty to use defaults)
   */
  seo?: {
    /**
     * Override default title (max 60 chars)
     */
    metaTitle?: string | null;
    /**
     * Override default description (max 160 chars)
     */
    metaDescription?: string | null;
  };
  /**
   * Additional SEO content for bottom of page
   */
  seoContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Number of products (auto-calculated)
   */
  productCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe this image for accessibility and SEO
   */
  alt: string;
  /**
   * Optional caption
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * Full product name
   */
  name: string;
  /**
   * Short name for listings (optional)
   */
  shortName?: string | null;
  /**
   * URL-safe identifier
   */
  slug: string;
  /**
   * Internal product code
   */
  sku: string;
  status: 'draft' | 'published' | 'discontinued';
  /**
   * Main category (used in URL)
   */
  primaryCategory: string | Category;
  /**
   * Additional categories
   */
  categories?: (string | Category)[] | null;
  brand: string | Brand;
  /**
   * Brief description (50+ words, used for meta description)
   */
  shortDescription: string;
  /**
   * Full product description (300+ words for SEO)
   */
  fullDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Technical specifications
   */
  specifications?:
    | {
        label: string;
        value: string;
        /**
         * e.g., kg, mm, pcs
         */
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * External image URL (e.g., from supplier CDN)
   */
  externalImageUrl?: string | null;
  /**
   * Main product image (overrides external URL)
   */
  primaryImage?: (string | null) | Media;
  /**
   * Additional product images
   */
  images?: (string | Media)[] | null;
  /**
   * PDF datasheet/specification document
   */
  datasheet?: (string | null) | Media;
  /**
   * How customers can purchase this product
   */
  purchaseMode: 'both' | 'buy-online' | 'rfq-only';
  pricing?: {
    /**
     * Standard unit price (leave empty for RFQ-only)
     */
    basePrice?: number | null;
    /**
     * e.g., per piece, per box, per 100
     */
    priceUnit?: string | null;
    currency?: ('USD' | 'CAD') | null;
    /**
     * Volume discount tiers
     */
    tieredPricing?:
      | {
          /**
           * Minimum quantity
           */
          minQty: number;
          /**
           * Maximum quantity (leave empty for no limit)
           */
          maxQty?: number | null;
          /**
           * Price per unit at this tier
           */
          unitPrice: number;
          id?: string | null;
        }[]
      | null;
    /**
     * Original price before discount (strikethrough display)
     */
    compareAtPrice?: number | null;
  };
  availability: 'in-stock' | 'made-to-order' | 'contact';
  /**
   * Minimum order quantity
   */
  minOrderQuantity?: number | null;
  /**
   * Number of units per package (e.g., 12 gloves per box)
   */
  packageQty?: number | null;
  /**
   * Package unit label (e.g., box, case, pack, roll)
   */
  packageUnit?: string | null;
  /**
   * e.g., 2-3 weeks, Ships in 1 day
   */
  leadTime?: string | null;
  /**
   * Shipping weight and processing time
   */
  shippingInfo?: {
    /**
     * Actual product weight in kg (used for shipping calculation)
     */
    weight?: number | null;
    /**
     * Days needed to prepare for shipment (default: 3)
     */
    processingTime?: number | null;
  };
  /**
   * Filterable attributes
   */
  facets?: {
    /**
     * e.g., Nitrile, Leather, Cotton
     */
    material?: string[] | null;
    /**
     * e.g., S, M, L, XL
     */
    size?: string[] | null;
    /**
     * e.g., Blue, Black, White
     */
    color?: string[] | null;
    /**
     * e.g., ANSI, CE, ISO 9001
     */
    certification?: string[] | null;
  };
  /**
   * Related products for cross-selling
   */
  relatedProducts?: (string | Product)[] | null;
  industries?:
    | (
        | 'manufacturing'
        | 'construction'
        | 'automotive'
        | 'healthcare'
        | 'food-beverage'
        | 'warehouse'
        | 'oil-gas'
        | 'mining'
      )[]
    | null;
  /**
   * SEO overrides
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Primary keyword for this product
     */
    focusKeyword?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: string;
  name: string;
  slug: string;
  /**
   * Brand logo
   */
  logo?: (string | null) | Media;
  /**
   * Brand description (minimum 200 words for SEO)
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Official brand website URL
   */
  website?: string | null;
  /**
   * Show in featured brands section
   */
  featured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  orderNumber: string;
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  paymentStatus: 'unpaid' | 'paid' | 'refunded';
  customer: {
    name: string;
    email: string;
    phone?: string | null;
    company: string;
  };
  items: {
    product: string | Product;
    /**
     * Snapshot of product name at time of order
     */
    productName: string;
    sku: string;
    quantity: number;
    /**
     * Price per unit at time of order
     */
    unitPrice: number;
    lineTotal: number;
    id?: string | null;
  }[];
  shipping: {
    address: string;
    city: string;
    state: string;
    postalCode: string;
    /**
     * Country code, e.g. US, CA, HK, GB
     */
    country: string;
    method?: string | null;
    trackingNumber?: string | null;
    /**
     * Selected shipping method code, e.g. "standard", "economy"
     */
    shippingMethodCode?: string | null;
    /**
     * Snapshot of shipping method display name
     */
    shippingMethodName?: string | null;
    /**
     * Calculated ship date (ISO string)
     */
    estimatedShipDate?: string | null;
    /**
     * Calculated delivery date (ISO string)
     */
    estimatedDeliveryDate?: string | null;
    /**
     * Total chargeable weight in kg
     */
    totalWeight?: number | null;
  };
  subtotal: number;
  shippingCost?: number | null;
  tax?: number | null;
  total: number;
  currency?: ('USD' | 'HKD' | 'EUR' | 'GBP' | 'CAD' | 'CNY') | null;
  payment?: {
    method?: ('stripe' | 'bank-transfer') | null;
    /**
     * Stripe Checkout Session ID
     */
    stripeSessionId?: string | null;
    /**
     * Stripe Payment Intent ID
     */
    stripePaymentIntentId?: string | null;
    transactionId?: string | null;
  };
  /**
   * Notes from the customer at checkout
   */
  customerNotes?: string | null;
  assignedTo?: (string | null) | User;
  /**
   * Internal notes
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bank-accounts".
 */
export interface BankAccount {
  id: string;
  /**
   * Display name, e.g. "USD - HSBC Hong Kong"
   */
  accountName: string;
  /**
   * Country name in English, e.g. "Hong Kong", "United States"
   */
  country: string;
  /**
   * ISO 3166-1 alpha-2 code, e.g. "HK", "US", "DE"
   */
  countryCode: string;
  /**
   * Flag emoji, e.g. "🇭🇰", "🇺🇸"
   */
  flag?: string | null;
  currency:
    | 'USD'
    | 'HKD'
    | 'EUR'
    | 'GBP'
    | 'CAD'
    | 'CNY'
    | 'AUD'
    | 'NZD'
    | 'SGD'
    | 'AED'
    | 'MXN'
    | 'PHP'
    | 'IDR'
    | 'ILS'
    | 'DKK';
  bankName: string;
  beneficiaryName: string;
  /**
   * Account number, IBAN, or local account format
   */
  accountNumber: string;
  /**
   * Local routing code: IBAN (EU), Routing Number (US), BSB (AU), Sort Code (UK), etc.
   */
  localBankCode?: string | null;
  /**
   * Label for local code, e.g. "IBAN", "Routing Number", "BSB", "Sort Code"
   */
  localBankCodeLabel?: string | null;
  /**
   * SWIFT/BIC code for international transfers
   */
  swiftCode?: string | null;
  bankAddress?: string | null;
  /**
   * Any additional payment instructions
   */
  additionalInfo?: string | null;
  isActive?: boolean | null;
  /**
   * Lower numbers appear first
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfq-submissions".
 */
export interface RfqSubmission {
  id: string;
  displayTitle?: string | null;
  submittedAt: string;
  customer: {
    name: string;
    email: string;
    phone?: string | null;
    company: string;
    /**
     * Job title
     */
    title?: string | null;
  };
  inquiry: {
    /**
     * Products the customer is inquiring about
     */
    products?: (string | Product)[] | null;
    /**
     * Requested quantity
     */
    quantity?: number | null;
    /**
     * Customer message/requirements
     */
    message: string;
    /**
     * Specification documents, drawings, etc.
     */
    attachments?: (string | Media)[] | null;
  };
  status: 'new' | 'contacted' | 'quoted' | 'converted' | 'lost';
  /**
   * Sales representative
   */
  assignedTo?: (string | null) | User;
  /**
   * Internal notes (not visible to customer)
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  source?: {
    /**
     * Page where form was submitted
     */
    page?: string | null;
    /**
     * Referrer URL
     */
    referrer?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  displayTitle?: string | null;
  submittedAt: string;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  subject: 'general' | 'support' | 'order' | 'return' | 'partnership' | 'other';
  message: string;
  status: 'new' | 'replied' | 'resolved';
  /**
   * Internal notes
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-methods".
 */
export interface ShippingMethod {
  id: string;
  /**
   * Display name, e.g. "Standard Air Shipping"
   */
  name: string;
  /**
   * Internal code, e.g. "standard", "economy"
   */
  code: string;
  /**
   * Transit time in calendar days (not displayed to buyer, used for ETA calculation)
   */
  transitDays: number;
  /**
   * Customer-facing description of shipping service
   */
  description?: string | null;
  isActive?: boolean | null;
  /**
   * Lower numbers appear first
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-rates".
 */
export interface ShippingRate {
  id: string;
  /**
   * Auto-generated from method + country
   */
  displayName?: string | null;
  /**
   * Which shipping method this rate applies to
   */
  shippingMethod: string | ShippingMethod;
  /**
   * ISO country code e.g. "US", "DE", "GB". Use "OTHER" as fallback for unlisted countries.
   */
  countryCode: string;
  /**
   * Display name e.g. "United States", "Germany"
   */
  countryName?: string | null;
  /**
   * Included base weight (kg)
   */
  baseWeight: number;
  /**
   * Cost for base weight (USD)
   */
  baseRate: number;
  /**
   * Cost per kg above base weight (USD)
   */
  additionalRate: number;
  /**
   * Flat handling/processing fee (USD)
   */
  handlingFee: number;
  isActive?: boolean | null;
  /**
   * Internal notes
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "free-shipping-rules".
 */
export interface FreeShippingRule {
  id: string;
  /**
   * e.g. "Economy Free Shipping $500+"
   */
  name: string;
  /**
   * Which shipping method this threshold applies to
   */
  shippingMethod: string | ShippingMethod;
  /**
   * Leave blank for global, or set ISO code (e.g. "US") for country-specific rule
   */
  countryCode?: string | null;
  /**
   * Minimum order subtotal (USD) to qualify for free shipping
   */
  minimumAmount: number;
  /**
   * Custom prompt template, e.g. "Add ${gap} more for free shipping!"
   */
  message?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-codes".
 */
export interface VerificationCode {
  id: string;
  email: string;
  code: string;
  expiresAt: string;
  attempts?: number | null;
  verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-sessions".
 */
export interface AccountSession {
  id: string;
  email: string;
  token: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product view logs for recommendation engine
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productViews".
 */
export interface ProductView {
  id: string;
  product: string | Product;
  /**
   * Anonymous session identifier (from cookie/localStorage)
   */
  sessionId: string;
  viewedAt: string;
  /**
   * Page URL that led to this product view
   */
  referrer?: string | null;
  /**
   * Browser user agent string
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog posts, buying guides, and knowledge articles for SEO and content marketing
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  /**
   * Article title — include target keyword naturally
   */
  title: string;
  /**
   * URL slug (auto-generated from title if left empty)
   */
  slug: string;
  /**
   * Short summary shown on cards and in meta description (max 300 chars)
   */
  excerpt: string;
  /**
   * Full article content. Use headings (H2, H3) for structure.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Primary content category
   */
  category: 'buying-guide' | 'industry-insight' | 'how-to' | 'product-comparison';
  /**
   * Tags for filtering (e.g. "safety", "adhesives", "manufacturing")
   */
  tags?: string[] | null;
  /**
   * Author name displayed on the article
   */
  author?: string | null;
  /**
   * Featured image for article cards and hero section
   */
  featuredImage?: (string | null) | Media;
  /**
   * Only published articles appear on the site
   */
  status: 'draft' | 'published';
  /**
   * Publication date (auto-set when status changes to published)
   */
  publishedAt?: string | null;
  /**
   * Products to display at the bottom of the article
   */
  relatedProducts?: (string | Product)[] | null;
  /**
   * Related product categories for internal linking
   */
  relatedCategories?: (string | Category)[] | null;
  /**
   * SEO overrides (leave empty to auto-generate from title/excerpt)
   */
  seo?: {
    /**
     * Custom meta title (max 60 chars). Defaults to article title.
     */
    metaTitle?: string | null;
    /**
     * Custom meta description (max 160 chars). Defaults to excerpt.
     */
    metaDescription?: string | null;
  };
  /**
   * Estimated reading time in minutes (auto-calculated)
   */
  readingTime?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'brands';
        value: string | Brand;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'bank-accounts';
        value: string | BankAccount;
      } | null)
    | ({
        relationTo: 'rfq-submissions';
        value: string | RfqSubmission;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'shipping-methods';
        value: string | ShippingMethod;
      } | null)
    | ({
        relationTo: 'shipping-rates';
        value: string | ShippingRate;
      } | null)
    | ({
        relationTo: 'free-shipping-rules';
        value: string | FreeShippingRule;
      } | null)
    | ({
        relationTo: 'verification-codes';
        value: string | VerificationCode;
      } | null)
    | ({
        relationTo: 'account-sessions';
        value: string | AccountSession;
      } | null)
    | ({
        relationTo: 'productViews';
        value: string | ProductView;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  description?: T;
  shortDescription?: T;
  introContent?: T;
  buyingGuide?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  heroImage?: T;
  icon?: T;
  featured?: T;
  displayOrder?: T;
  facetGroups?:
    | T
    | {
        facetName?: T;
        expanded?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  seoContent?: T;
  productCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  slug?: T;
  sku?: T;
  status?: T;
  primaryCategory?: T;
  categories?: T;
  brand?: T;
  shortDescription?: T;
  fullDescription?: T;
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        unit?: T;
        id?: T;
      };
  externalImageUrl?: T;
  primaryImage?: T;
  images?: T;
  datasheet?: T;
  purchaseMode?: T;
  pricing?:
    | T
    | {
        basePrice?: T;
        priceUnit?: T;
        currency?: T;
        tieredPricing?:
          | T
          | {
              minQty?: T;
              maxQty?: T;
              unitPrice?: T;
              id?: T;
            };
        compareAtPrice?: T;
      };
  availability?: T;
  minOrderQuantity?: T;
  packageQty?: T;
  packageUnit?: T;
  leadTime?: T;
  shippingInfo?:
    | T
    | {
        weight?: T;
        processingTime?: T;
      };
  facets?:
    | T
    | {
        material?: T;
        size?: T;
        color?: T;
        certification?: T;
      };
  relatedProducts?: T;
  industries?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        focusKeyword?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  description?: T;
  website?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  paymentStatus?: T;
  customer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        company?: T;
      };
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        sku?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        id?: T;
      };
  shipping?:
    | T
    | {
        address?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        method?: T;
        trackingNumber?: T;
        shippingMethodCode?: T;
        shippingMethodName?: T;
        estimatedShipDate?: T;
        estimatedDeliveryDate?: T;
        totalWeight?: T;
      };
  subtotal?: T;
  shippingCost?: T;
  tax?: T;
  total?: T;
  currency?: T;
  payment?:
    | T
    | {
        method?: T;
        stripeSessionId?: T;
        stripePaymentIntentId?: T;
        transactionId?: T;
      };
  customerNotes?: T;
  assignedTo?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bank-accounts_select".
 */
export interface BankAccountsSelect<T extends boolean = true> {
  accountName?: T;
  country?: T;
  countryCode?: T;
  flag?: T;
  currency?: T;
  bankName?: T;
  beneficiaryName?: T;
  accountNumber?: T;
  localBankCode?: T;
  localBankCodeLabel?: T;
  swiftCode?: T;
  bankAddress?: T;
  additionalInfo?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfq-submissions_select".
 */
export interface RfqSubmissionsSelect<T extends boolean = true> {
  displayTitle?: T;
  submittedAt?: T;
  customer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        company?: T;
        title?: T;
      };
  inquiry?:
    | T
    | {
        products?: T;
        quantity?: T;
        message?: T;
        attachments?: T;
      };
  status?: T;
  assignedTo?: T;
  notes?: T;
  source?:
    | T
    | {
        page?: T;
        referrer?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  displayTitle?: T;
  submittedAt?: T;
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  subject?: T;
  message?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-methods_select".
 */
export interface ShippingMethodsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  transitDays?: T;
  description?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-rates_select".
 */
export interface ShippingRatesSelect<T extends boolean = true> {
  displayName?: T;
  shippingMethod?: T;
  countryCode?: T;
  countryName?: T;
  baseWeight?: T;
  baseRate?: T;
  additionalRate?: T;
  handlingFee?: T;
  isActive?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "free-shipping-rules_select".
 */
export interface FreeShippingRulesSelect<T extends boolean = true> {
  name?: T;
  shippingMethod?: T;
  countryCode?: T;
  minimumAmount?: T;
  message?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-codes_select".
 */
export interface VerificationCodesSelect<T extends boolean = true> {
  email?: T;
  code?: T;
  expiresAt?: T;
  attempts?: T;
  verified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-sessions_select".
 */
export interface AccountSessionsSelect<T extends boolean = true> {
  email?: T;
  token?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productViews_select".
 */
export interface ProductViewsSelect<T extends boolean = true> {
  product?: T;
  sessionId?: T;
  viewedAt?: T;
  referrer?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  tags?: T;
  author?: T;
  featuredImage?: T;
  status?: T;
  publishedAt?: T;
  relatedProducts?: T;
  relatedCategories?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  readingTime?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}