-- Add missing columns for migration

-- Brands table
ALTER TABLE brands ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT false;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS seo JSONB;

-- Articles table
ALTER TABLE articles ADD COLUMN IF NOT EXISTS reading_time INTEGER;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS related_categories TEXT[];
ALTER TABLE articles ADD COLUMN IF NOT EXISTS excerpt TEXT;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS seo JSONB;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS featured_image TEXT;

-- Products table
ALTER TABLE products ADD COLUMN IF NOT EXISTS seo JSONB;
ALTER TABLE products ADD COLUMN IF NOT EXISTS facets JSONB;
ALTER TABLE products ADD COLUMN IF NOT EXISTS industries TEXT[];
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS primary_category TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS category TEXT[];
ALTER TABLE products ADD COLUMN IF NOT EXISTS external_image_url TEXT;
